package com.cybozu.labs.langdetect.util;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
/**
 * This is {@link Messages} class generated by Eclipse automatically. Users don't use this class directly.
 * @author Nakatani Shuyo
 */
public class Messages
{
	// $NON-NLS-1$
    	private static final String BUNDLE_NAME = "com.cybozu.labs.langdetect.util.messages";
    	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);
    	/**
	 * Create messages
	 */
	private Messages()
	{
    	}

	/**
	 * Get the messages
	 * @key - the key to return
	 * @return Returns the string from the messages
	 */
    	public static String getString(String key)
	{
        	try
		{
            		return RESOURCE_BUNDLE.getString(key);
        	}
		catch (MissingResourceException e)
		{
            		return '!' + key + '!';
        	}
    	}
}
